"""Добавлен статус Enum в Bet

Revision ID: a7954a7965bf
Revises: 
Create Date: 2024-11-02 15:45:29.766411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from config.database import Base


# revision identifiers, used by Alembic.
revision: str = 'a7954a7965bf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('abstract_instance',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_abstract_instance_id'), 'abstract_instance', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('balance', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username'),
    postgresql_inherits='abstract_instance'
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('bet',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bet', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('ongoing', 'team1_win', 'team2_win', name='eventstatus'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    postgresql_inherits='abstract_instance'
    )
    op.create_index(op.f('ix_bet_id'), 'bet', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bet_id'), table_name='bet')
    op.drop_table('bet')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_abstract_instance_id'), table_name='abstract_instance')
    op.drop_table('abstract_instance')
    # ### end Alembic commands ###
